server:
  port: 8006
#  address: 172.31.37.211

spring:
  datasource:
    ##    driver-class-name: org.mariadb.jdbc.Driver
    ##    url: jdbc:mariadb://127.0.0.1:3308/allmytour_admin
    #    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #    url: jdbc:log4jdbc:mariadb://127.0.0.1:3308/allmytour_admin
    #    password: santa4886
    #    username: root
    ##    driver-class-name: org.mariadb.jdbc.Driver
    ##    url: jdbc:mariadb://27.96.131.207:3306/allmytourdb


    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://twepo.cbmostrietd6.ap-northeast-2.rds.amazonaws.com:3306/flowmaker?&allowMultiQueries=true
    url: jdbc:mariadb://twepo.cbmostrietd6.ap-northeast-2.rds.amazonaws.com:3306/flowmaker
    username: admin
    password: santa4886



#server:
#  port: 8007

#spring:
#  #  jpa:
#  #    hibernate:
#  #      ddl-auto:none
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://twepo.cbmostrietd6.ap-northeast-2.rds.amazonaws.com:3306/flowmaker
#    username: admin
#    password: santa4886

