server:
  port: 8050



spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://twepo.cbmostrietd6.ap-northeast-2.rds.amazonaws.com:3306/flowmaker
    username: admin
    password: santa4886


